# Database for week 1  containing Taxi Data

version: '3.1'

services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./ny_taxi_postgres_data_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ny_taxi
