# Database for week 1  containing Taxi Data
#
# Database type: PostgreSQL
# Database name: ny_taxi
# Database username: root
# Database password: root

version: '3.1'

services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi

    



  